// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8IqO5KyN-HF_CSjVxqIIG3d5uFcAhO4',
    appId: '1:931997234707:web:44a3d9708f5d40af9271e6',
    messagingSenderId: '931997234707',
    projectId: 'whatsapp-clone-264a1',
    authDomain: 'whatsapp-clone-264a1.firebaseapp.com',
    storageBucket: 'whatsapp-clone-264a1.firebasestorage.app',
    measurementId: 'G-92YVDC9ZH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3n8mcri54F0nOwDpQs3EaK9eroy-n9vg',
    appId: '1:931997234707:android:a2e0d54509cf22159271e6',
    messagingSenderId: '931997234707',
    projectId: 'whatsapp-clone-264a1',
    storageBucket: 'whatsapp-clone-264a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTIUbaJWqY6Yqbh4tBy8u8vvN7wKCIHo',
    appId: '1:931997234707:ios:e4c006075b5c3f7a9271e6',
    messagingSenderId: '931997234707',
    projectId: 'whatsapp-clone-264a1',
    storageBucket: 'whatsapp-clone-264a1.firebasestorage.app',
    androidClientId: '931997234707-e2g62i1top6hp5f0anugqq4jliideqa7.apps.googleusercontent.com',
    iosClientId: '931997234707-9d2v8k2r3lgpvk1i0o5fa1g77j3n5ipl.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTIUbaJWqY6Yqbh4tBy8u8vvN7wKCIHo',
    appId: '1:931997234707:ios:e4c006075b5c3f7a9271e6',
    messagingSenderId: '931997234707',
    projectId: 'whatsapp-clone-264a1',
    storageBucket: 'whatsapp-clone-264a1.firebasestorage.app',
    androidClientId: '931997234707-e2g62i1top6hp5f0anugqq4jliideqa7.apps.googleusercontent.com',
    iosClientId: '931997234707-9d2v8k2r3lgpvk1i0o5fa1g77j3n5ipl.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL8IqO5KyN-HF_CSjVxqIIG3d5uFcAhO4',
    appId: '1:931997234707:web:0adb752d0325bda19271e6',
    messagingSenderId: '931997234707',
    projectId: 'whatsapp-clone-264a1',
    authDomain: 'whatsapp-clone-264a1.firebaseapp.com',
    storageBucket: 'whatsapp-clone-264a1.firebasestorage.app',
    measurementId: 'G-19B9H70904',
  );
}
